05 homework tests
StasAvramov/goit-nodejs-hw pull request #6
Opened 2020-10-13 16:31 UTC by StasAvramov

2020-10-13 22:00 UTC, StasAvramov commented
Кажется более- менее похоже на правду. Но не знаю как быть с verifyToken.

2020-10-15 20:20 UTC, StasAvramov commented
1й тест отрабатывает всегда.

2й тест крашится на строке  expect(fakeVerifyToken).to.throw(Error);
Выдает такую ошибку AssertionError: expected [Function: functionStub] to throw Error
Думаю, что у меня проблема в описании заглушки:
const fakeVerifyToken = sinon.stub(); // создаю функцию заглушку
  fakeVerifyToken.withArgs(invalidToken).throws(new Error("Invalid Token")); //при вызове с invalidToken выбрасывает ошибку
  fakeVerifyToken.withArgs(validToken).returns({ id: 123 }); // при вызове с validToken возвращает объект {id:123}
Если закоментить строку  expect(fakeVerifyToken).to.throw(Error); то он проходит.

3й тест тоже крашится на ожиданиях работы fakeVerifyToken: 
expect(fakeVerifyToken.calledOnce).to.be.true; //AssertionError: expected false to be true
 expect(fakeVerifyToken.firstCall.args[0]).to.be.equal(validToken); //AssertionError: expected invalidToken to equal validToken

Я старался, но не знаю в чем беда. Help please)

2020-10-16 09:37 UTC, odykyi commented on tests/auth.middleware.test.js
> +    expect(fakeVerifyToken).to.throw(Error);*/
here is your issue 

https://stackoverflow.com/questions/21587122/mocha-chai-expect-to-throw-not-catching-thrown-errors

2020-10-16 09:39 UTC, odykyi commented on tests/auth.middleware.test.js
> +  it("Passed token is invalid", async () => {
по этому второму тесту думаю что вы справитесь 
с подсказкой с стековерфлова

2020-10-16 09:40 UTC, odykyi commented on tests/auth.middleware.test.js
> +  it("Passed token is invalid", async () => {
по второму тесту вы правильно двигаетесь

хорошо что вы обрабатываете положительные и отрицательные кейсы

2020-10-16 09:42 UTC, odykyi commented on tests/auth.middleware.test.js
> +    // expect(fakeVerifyToken.calledOnce).to.be.true;
он не будет calledOnce true потому что он уже вызывался во втором тесте

создайте новый fakeVerifyToken и вызывайте его опять

2020-10-16 09:42 UTC, odykyi requested changes
comments

2020-10-16 11:51 UTC, odykyi commented on tests/auth.middleware.test.js
> +    expect(() => fakeVerifyToken(invalidToken)).to.throw(Error);
good solution!

2020-10-16 11:51 UTC, odykyi approved these changes

2020-10-16 11:52 UTC, merged